# Generated by Django 5.0.1 on 2024-02-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.user",
            ),
        ),
    ]
